### ISSUE TITLE
Rename promise.otherwise() to promise.catch()

### ISSUE THREAD

**Issue by galves** [ef-labs/when.java#7]
This would make it aligned with ES6 promises and most other implementations I have come across.  It is also more idiomatic from a Java perspective in my opinion.

Thanks

**Comment by adrianluisgonzalez** [comment]
I don't believe this is possible, `catch` is a reserved word in Java.  https://en.wikipedia.org/wiki/List_of_Java_keywords

**Comment by galves** [comment]
Excellent point!
